### ISSUE TITLE
Cannot load converter in WATS client

### ISSUE THREAD

**Issue by MOKJ** [Virinco/WATS-Client-Converter-Listen#4]
Hi Virinco

I have followed the guide for installing the Listen converter. (https://github.com/Virinco/WATS-Client-Converter-Listen).

I installed WATS client 6.0.0.192 (64bits).
I have successfully logged into my account in the client. 
I downloaded the Listen converter. 
I created a new converter. Loaded the .dll from the Listen .zip file. 
Error: the class field is empty.

Hope you can help

Br,
Morten

**Comment by AhNesh** [comment]
Hi,

Try unblocking the file (or the zip)

![image](https://user-images.githubusercontent.com/33862238/107776345-ba402580-6d41-11eb-9805-5f530c7173dd.png)

**Comment by MOKJ** [comment]
Thank you. After unblocking the file, the issue is gone.
